### PR TITLE
The onboarding is now opened in a single click of show onboarding button

### LINKED ISSUE #86: Demos: fix open onboarding button
The (?) open onboarding button needs to be clicked twice currently so that the onboarding gets opened. Actually, it should already open up after the first click. (There must be something wrong with the initial state)

### PR DESCRIPTION
**Pull request by dvsilviyageo**
closes #86 

Summary of Changes
* The showOnboarding is set to true when the showOnboarding icon is clicked.
* The changes are made in all the three packages plotly, Echart and Vega-Lite.

### CODE REVIEW

File: packages/echarts-demo/src/bar-chart.js [hunk 1]
```diff
@@ -98,6 +98,7 @@ const getAhoiConfig = () => {
 }
 
 const registerEventListener = () => {
+  showOnboarding = !showOnboarding;
   const helpIcon = document.getElementById("show-onboarding");
   if(!helpIcon) { return; }
   helpIcon.addEventListener('click', async () => {
```
Comment (dvdanielamoitzi) [inline packages/echarts-demo/src/bar-chart.js:104]: Moving up the `showOnboarding = !showOnboarding;` from line 110 to line 104 (before the if) should do the trick without changing the flag when the event listener is registered. Please change it for all demos. You can then remove line 101.

**Review by dvdanielamoitzi — APPROVED** [review]
